In [50]:
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import mysql.connector

# 1) Configuration de google sheet

champ_application = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
References = ServiceAccountCredentials.from_json_keyfile_name("Credentials.json", champ_application)
client = gspread.authorize(References)

# Ouverture du classeur
spreadsheet = client.open_by_url("https://docs.google.com/spreadsheets/d/10-BCkQZltFQWibW4gFz9Wfj8dED4-hEVjwcBNRf7FKM/edit?usp=sharing")
worksheet = spreadsheet.worksheet('Réponses au formulaire 3')

# Lire les données
records = worksheet.get_all_records()
df = pd.DataFrame(records)


df

,Horodateur,prénom,nom,téléphone1,téléphone2,email,diplome,sexe,age,profession,...,region_origine,membership,programme_intervention,En quelle qualité êtes-vous intervenus ?,année_intervention,Quelle thématique avez-vous abordé?,programme,année,pole,Souhaitez-vous figurer dans l'annuaire The Okwelians ?\nWould you like to be listed in The Okwelians' directory ?
0,21/02/2024 10:33:39,Dorine,MBONGALLE,237690308615,,dmbongalle@gmail.com,Post graduate dimplomat,Une femme,31-35 ans/ 31-35 years,Banker,...,Sud-Ouest / South-West,Membre de la family/ Member of The Family,,,,,,,,
1,21/02/2024 10:48:26,apolline,keou,237651514392,,apollinekeou@yahoo.fr,MASTER 2 EN MANAGEMENT - Master 2 en ingenierie,Une femme,Supérieur à 35 ans/ Above 35 years,Consultant en management et organisation,...,Ouest / West,Membre de la family/ Member of The Family,,,,,,,Équipe Exécutive / Executif team,
2,22/02/2024 17:20:38,Daïrou,Faridatou,693738385,,dairoufarida@gmail.com,Master 1,Une femme,18-25 ans/ 18-25 years,Étudiante,...,Nord / North,Lauréat.e/ Laureate,,,,,O'100,2022,Engagement/ Engagement,
3,25/02/2024 22:26:03,Hervé,Djia,237675858914,,djiathink@gmail.com,Master II Computer Science,Un homme,Supérieur à 35 ans/ Above 35 years,Consultant Système d’information,...,Ouest / West,Membre de la family/ Member of The Family,,,,,,,,
4,25/02/2024 22:27:48,Derrick,DANG A GOUFAN,675368159,,derrickdang15@yahoo.fr,Doctorat,Un homme,31-35 ans/ 31-35 years,Enseignant Chercheur,...,Centre / Center,Lauréat.e/ Laureate,,,,,CC (Campus chercheur),2022,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,23/05/2025 12:43:58,Youssouf,NVUH NJOYA,237699166710,,nnynjoya2001@yahoo.fr,Doctorat / PhD,Un homme / A man,26/01/1985,Enseignant / Teacher,...,Ouest / West,Membre de la family/ Member of The Family,,,,,,,LaB/ LaB,Oui
866,23/05/2025 13:13:28,Marthe,Aguimke Doubla,+ 237 698483854,,martheaguimkedoubla@gmail.com,Master / Master's degree,Une femme / A woman,10/08/1992,Étudiant / Student,...,Extrême Nord / Farth-North,Membre de la family/ Member of The Family,,,,,,,,Oui
867,23/05/2025 15:54:16,Merlin noel,YETNA BOUM,237696148472,,artistemerlino@gmail.com,"BEPC / GCE ""O"" Level",Un homme / A man,19/07/0086,Artiste / Artist,...,Littoral / Littoral,Participant aux ateliers / workshop participants,,,,,,,,Oui
868,23/05/2025 16:07:19,Ahmadou,Moustafa Ahidjo,+237 699650065,+237 670076766,ahmadoumoustafaahidjo@yahoo.fr,Master / Master's degree,Un homme / A man,12/03/1990,Sans emploi /,...,Nord / North,Membre de la family/ Member of The Family,,,,,,,,Oui
869,23/05/2025 17:30:15,Marie Bernadette,KAFKA,237690789343,237678721809,mariebernadettekafka@gmail.com,Master / Master's degree,Une femme / A woman,09/12/1999,Entrepreneur / Entrepreneur,...,Centre / Center,Mentor/Formateur/Intervenant/Modérateur,Médiateurs de la démocratie,,2025,,,,Communication et Marketing/ Communication and ...,Oui

In [51]:
#Transformer les données

df['nom'] = df['nom'].str.upper()
df['prénom'] = df['prénom'].str.capitalize()
df["diplome"] = df['diplome'].replace({"Master / Master's degree" : "Master",
                                       "Licence / Bachelor's degree" : "Licence",
                                       'Baccalauréat / GCE "A" Level' : "Baccalauréat",
                                       'BEPC / GCE "O" Level' : "BEPC",
                                       "BTS / Advanced Technician's Certificate" : "BTS",
                                       "DUT / Two-year university degree in technology" : "DUT",
                                       "Doctorat / PhD" : "Doctorat",
                                       "Diplôme d'ingénieur / Engineering degree" : "Diplôme d'ingénieur",
                                       "GCE Alevel" : "Baccalauréat",
                                       "Master 2" : "Master",
                                       "Bac+3" : "Licence",
                                       "GCE A/L" : "Baccalauréat",
                                       "Master1 " : "Maîtrise",
                                       "GCE A level" : "Baccalauréat",
                                       "Doctor of Medicine degree " : "Doctorat (Santé)",
                                       "Master 2 Gestion des Ressources Humaines " : "Master",
                                       "B.e.p.c" : "BEPC",
                                       "Ingénieur de conception en maintenance industrielle et productique" : "Diplôme d'ingénieur",
                                       "Licence en Audit et contrôle " : "Licence",
                                       "ingénieur de conception pétrole et gaz " : "Diplôme d'ingénieur",
                                       "Bts cge" : "BTS",
                                       "Mastère Spécialisé en marché des énergies" : "Master",
                                       "Master en sociologie" : "Master",
                                       "Ingénieur Halieute" : "Diplôme d'ingénieur",
                                       "Baccalauréat A4" : "Baccalauréat",
                                       "Master's Degree" : "Master",
                                       "Master II" : "Master",
                                       "Master 1 en droit et administration publique" : "Maîtrise",
                                       "Master II en Marketing" : "Master",
                                       "Bac +3 en Informatique" : "Licence",
                                       "Bsc in Marketing" : "Licence",
                                       "MASTER 2 EN SCIENCE DE GESTION - COMPTABILITÉ CONTRÔLE AUDIT" : "Master",
                                       "Licence en lettes d'expression Française" : "Licence",
                                       "Diplôme d'ingénieur de conception" : "Diplôme d'ingénieur",
                                       "Ingénieur de Conception en Génie Mécanique" : "Diplôme d'ingénieur",
                                       "MSc in International Business and Management" : "Master",
                                       "Master II recherche" : "Master",
                                       "BACCALAUREAT" : "Baccalauréat",
                                       "Bts" : "BTS",
                                       "MASTER" : "Master",
                                       "Master 2 en eau hygiène et assainissement" : "Master",
                                       "Bachelors degree" : "Licence",
                                       "Ingénieur" : "Diplôme d'ingénieur",
                                       "Diplôme d'ingénieur de conception" : "Diplôme d'ingénieur",
                                       "Licence Professionnelle" : "Licence",
                                       "Licence en physique mécanique" : "Licence",
                                       "Ingénieur" : "Diplôme d'ingénieur",
                                       "INGÉNIEUR DE CONCEPTION EN GÉNIE INFORMATIQUE" : "Diplôme d'ingénieur",
                                       "Licence en géographie physique" : "Licence",
                                       "Bac+3" : "Licence",
                                       "Master en Droit Public" : "Master",
                                       "Master 2 en psychologie" : "Master",
                                       "Licence en géographie humaine" : "Licence",
                                       "Master 2 Stratégie et Communication des marques" : "Master",
                                       "EMBA" : "Master",
                                       "Master Professionnel en maintenance et gestion des systèmes énergétiques" : "Master",
                                       "Diplôme d'ingénieur des travaux des télécommunications option informatique et réseaux" : "Diplôme d'ingénieur",
                                       "Master de spécialisation" : "Master",
                                       "Diplôme d'ingénieur en Génie Industriel" : "Diplôme d'ingénieur",
                                       "doctorat" : "Doctorat",
                                       "Master II Computer Science" : "Master",
                                       "MASTER 2 EN MANAGEMENT - Master 2 en ingenierie" : "Diplôme d'ingénieur",
                                       "Post graduate dimplomat" : "Master"})

df["sexe"] = df['sexe'].replace({"Une femme / A woman" : "Une femme",
                                 "Un homme / A man" : "Un homme"})

df["region_de_residence"] = df['region_de_residence'].replace({"Ouest / West" : "Ouest",
                                                     "Littoral / Littoral" : "Littoral",
                                                     "Est / East" : "Est",
                                                     "Centre / Center" : "Centre",
                                                     "Sud / South" : "Sud",
                                                     "Sud-Ouest / South-West" : "Sud-Ouest",
                                                     "Extrême Nord / Farth-North" : "Extrême-Nord",
                                                     "Nord / North" : "Nord",
                                                     "Nord-ouest / North-West" : "Nord-Ouest",
                                                     "Adamaoua / Adamaowa" : "Adamaoua"
                                                    })

df["region_origine"] = df['region_origine'].replace({"Ouest / West" : "Ouest",
                                                     "Littoral / Littoral" : "Littoral",
                                                     "Est / East" : "Est",
                                                     "Centre / Center" : "Centre",
                                                     "Sud / South" : "Sud",
                                                     "Sud-Ouest / South-West" : "Sud-Ouest",
                                                     "Extrême Nord / Farth-North" : "Extrême-Nord",
                                                     "Nord / North" : "Nord",
                                                     "Nord-ouest / North-West" : "Nord-Ouest",
                                                     "Adamaoua / Adamaowa" : "Adamaoua"
                                                    })

df["secteur"] = df['secteur'].replace({"Privé / Private" : "Privé",
                                                     "Public / Public" : "Public"
                                                    
                                                    })

df["secteur_activite"] = df['secteur_activite'].replace({"Economie/ Economy" : "Economie",
                                                     "Santé/ Health" : "Santé",
                                                         "ICT / Software Engineering" : "Informatique",
                                                         "Communication/ Communication" : "Communication",
                                                         "Education supérieure" : "Education",
                                                         "Environmental Sciences" : "Environment",
                                                         "Tech" : "Informatique",
                                                         "Agriculture/ Agriculture" : "Agriculture",
                                                         "Enseignement" : "Éducation",
                                                         "Non-travailleur" : "Chomage",
                                                         "NA" : "Chomage",
                                                         "Éducatif" : "Éducation",
                                                         "Aucune" : "Chomage",
                                                         "Technologie de l'information " : "Informatique",
                                                         "Education" : "Éducation",
                                                         "TIC" : "Informatique",
                                                         "INFORMATIQUE -TIC" : "Informatique",
                                                         "Politique/ Politics" : "Politique",
                                                         "ENSEIGNEMENT" : "Éducation",
                                                         "IT" : "Informatique",
                                                         "Civil society" : "société civile",
                                                         "Informatique et technologies" : "Informatique",
                                                         "Débrouille" : "Chomage"
                                                    })


df["profession"] = df['profession'].replace({"Étudiante" : "Étudiant",
                                                     "Au chômage " : "Sans emploi",
                                             "En recherche d'emploi" : "Sans emploi",
                                             "Aucune" : "Sans emploi",
                                             "Étudiant en ingénierie informatique" : "Étudiant",
                                             "Sans profession" : "Sans emploi",
                                             "Étudiants en master intégration régionale et management des institutions communautaires a l'IRIC .par ailleurs président de ORESAH ( ORGANISATION POUR LA RÉSILIENCE SOCIO-ÉCONOMIQUE ET L'ASSISTANCE HUMANITAIRE),RESPONSABLE RESSOURCES HUMAINES ET RENFORCEMENT DES CAPACITÉS A CIVAS. Responsable suivi-Évaluations a HURDA." : "Étudiant",
                                             "Aucun" : "Sans emploi",
                                             "Étudiants" : "Étudiant",
                                             "Étudiant / Student" : "Étudiant",
                                             "Aucune" : "Sans emploi",
                                             "Étudiant chercheur" : "Étudiant",
                                             "Étudiant et Assistant de recherche" : "Étudiant",
                                             "Job-searching" : "Sans emploi",
                                             "Etudiant en pharmacie" : "Étudiant",
                                             "Chercheuse d'emploi" : "Sans emploi",
                                             "Pour le moment je ne travaille pas " : "Sans emploi",
                                             "etudiante" : "Sans emploi",
                                             "Aucun" : "Sans emploi",
                                             "Jobless" : "Sans emploi",
                                             "I'm still searching for a job" : "Sans emploi",
                                             "student" : "Étudiant",
                                             "Student" : "Étudiant",
                                             "None" : "Étudiant",
                                             "Nothing" : "Sans emploi",
                                             "Ras" : "Sans emploi",
                                             "Etudiante" : "Étudiant",
                                             "Étudiant/ Jeune entrepreneur" : "Étudiant",
                                             "Élève ingénieur à l'école nationale supérieure polytechnique de Maroua" : "Étudiant",
                                             "À mon propre compte" : "Entrepreneur",
                                             "Étudiants/ peintre" : "Étudiant",
                                             "ELEVE PROFESSEUR" : "Étudiant",
                                             "Étudiant et entrepreneur" : "Entrepreneur",
                                             "Sans emploi (étudiant)" : "Étudiant",
                                             "APPRENANT AU CENTRE DE FORMATION PROFESDIONNELLE" : "Étudiant",
                                             "ÉTUDIANT" : "Étudiant",
                                             "Suis étudiante" : "Étudiant",
                                             "Etudiant Gestion des resources humaine" : "Étudiant",
                                             "ÉTUDIANT-ENTREPRENEUR" : "Entrepreneur",
                                             "ÉTUDIANTE CHERCHEUR" : "Étudiant",
                                             "I’m a student" : "Étudiant",
                                             "Student." : "Étudiant",
                                             "Entrepreneur / Entrepreneur" : "Entrepreneur",
                                             "Professionnel en marketing / Marketing professional" : "Professionnel en marketing",
                                             "Journaliste / Journalist" : "Journaliste",
                                             "Personnel de santé / Healthcare personnel" : "Personnel de santé",
                                             "Avocat / Lawyer" : "Avocat",
                                             "Étudiant / Student" : "Étudiant",
                                             "Enseignant / Teacher" : "Enseignant",
                                             "Ingénieur qualité / Quality engineer" : "Ingénieur qualité",
                                             "Responsable ressources humaines / Human resources manager" : "Responsable ressources humaines",
                                             "Artiste / Artist" : "Artiste",
                                             "Ingénieur agricole / Agricultural engineer" : "Ingénieur agricole",
                                             "Sans emploi /" : "Sans emploi",
                                             "Administrative Assistant/Tutor" : "Administrative Assistant",
                                             "Actuellement je suis sans emploi" : "Sans emploi"
                                             
                                                    
                                                    })

df["pole"] = df['pole'].replace({"Équipe Exécutive / Executif team" : "Équipe Exécutive",
                                                     "Engagement/ Engagement" : "Engagement",
                                 "LaB/ LaB" : "LaB",
                                 "Overseas/ Overseas" : "Overseas",
                                 "Communication et Marketing/ Communication and Marketing" : "Communication et Marketing",
                                 "Stratégie et Organisation/ Strategy and Organisation" : "Stratégie et Organisation",
                                 "Finance, Partenariats et Administratif/ Finance, Partnerships and Administration" : "Finance, Partenariats et Administratif",
                                 "Labo FIDEMO/ Labo FIDEMO" : "Labo FIDEMO",
                                 "Hub/ Hub" : "Hub"  
                                                    })
                                       
df

,Horodateur,prénom,nom,téléphone1,téléphone2,email,diplome,sexe,age,profession,...,region_origine,membership,programme_intervention,En quelle qualité êtes-vous intervenus ?,année_intervention,Quelle thématique avez-vous abordé?,programme,année,pole,Souhaitez-vous figurer dans l'annuaire The Okwelians ?\nWould you like to be listed in The Okwelians' directory ?
0,21/02/2024 10:33:39,Dorine,MBONGALLE,237690308615,,dmbongalle@gmail.com,Master,Une femme,31-35 ans/ 31-35 years,Banker,...,Sud-Ouest,Membre de la family/ Member of The Family,,,,,,,,
1,21/02/2024 10:48:26,Apolline,KEOU,237651514392,,apollinekeou@yahoo.fr,Diplôme d'ingénieur,Une femme,Supérieur à 35 ans/ Above 35 years,Consultant en management et organisation,...,Ouest,Membre de la family/ Member of The Family,,,,,,,Équipe Exécutive,
2,22/02/2024 17:20:38,Daïrou,FARIDATOU,693738385,,dairoufarida@gmail.com,Master 1,Une femme,18-25 ans/ 18-25 years,Étudiant,...,Nord,Lauréat.e/ Laureate,,,,,O'100,2022,Engagement,
3,25/02/2024 22:26:03,Hervé,DJIA,237675858914,,djiathink@gmail.com,Master II Computer Science,Un homme,Supérieur à 35 ans/ Above 35 years,Consultant Système d’information,...,Ouest,Membre de la family/ Member of The Family,,,,,,,,
4,25/02/2024 22:27:48,Derrick,DANG A GOUFAN,675368159,,derrickdang15@yahoo.fr,Doctorat,Un homme,31-35 ans/ 31-35 years,Enseignant Chercheur,...,Centre,Lauréat.e/ Laureate,,,,,CC (Campus chercheur),2022,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,23/05/2025 12:43:58,Youssouf,NVUH NJOYA,237699166710,,nnynjoya2001@yahoo.fr,Doctorat,Un homme,26/01/1985,Enseignant,...,Ouest,Membre de la family/ Member of The Family,,,,,,,LaB,Oui
866,23/05/2025 13:13:28,Marthe,AGUIMKE DOUBLA,+ 237 698483854,,martheaguimkedoubla@gmail.com,Master,Une femme,10/08/1992,Étudiant,...,Extrême-Nord,Membre de la family/ Member of The Family,,,,,,,,Oui
867,23/05/2025 15:54:16,Merlin noel,YETNA BOUM,237696148472,,artistemerlino@gmail.com,BEPC,Un homme,19/07/0086,Artiste,...,Littoral,Participant aux ateliers / workshop participants,,,,,,,,Oui
868,23/05/2025 16:07:19,Ahmadou,MOUSTAFA AHIDJO,+237 699650065,+237 670076766,ahmadoumoustafaahidjo@yahoo.fr,Master,Un homme,12/03/1990,Sans emploi,...,Nord,Membre de la family/ Member of The Family,,,,,,,,Oui
869,23/05/2025 17:30:15,Marie bernadette,KAFKA,237690789343,237678721809,mariebernadettekafka@gmail.com,Master,Une femme,09/12/1999,Entrepreneur,...,Centre,Mentor/Formateur/Intervenant/Modérateur,Médiateurs de la démocratie,,2025,,,,Communication et Marketing,Oui

In [52]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()

# 4) Selectionner les données
Lauréat = df[df['membership'] == 'Lauréat.e/ Laureate']
Elders = df[df['membership'] == 'Ainé / Elder']
Partenaire = df[df['membership'] == 'Partenaire/ Partner']
Family = df[df['membership'] == 'Membre de la family/ Member of The Family']
Adhérent = df[df['membership'] == 'Membre adhérent "membre cotisant"/ Subscribing member "contributing member"']
Mentor= df[df['membership'] == 'Mentor/Formateur/Intervenant/Modérateur']
Autres= df[df['membership'] .isin(["Participant aux ateliers / workshop participants", "Je m'engage pour l'Afrique", "Non admis aux programmes (OFYCL, O'100)"])]

 #✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM lauréats")

#-- Vérifiez si l'email existe
for _, row in Lauréat.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM Lauréats WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO lauréats (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, programme, année_programme, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['programme'], row['année'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

l'email supprimé: derrickdang15@yahoo.fr
l'email supprimé: natachamomo10@gmail.com
l'email supprimé: unkouefouette@gmail.com
l'email supprimé: wafoghislain2@gmail.com
l'email supprimé: armeladelaidensegue@gmail.com
l'email supprimé: alfredekango10@gmail.com
l'email supprimé: sommeleandelson@gmail.com
l'email supprimé: axeltagnef@gmail.com
l'email supprimé: mmakat71@gmail.com
l'email supprimé: amadoulabarang40@gmail.com
l'email supprimé: salecharlesjr@gmail.com
l'email supprimé: arolkache@gmail.com
l'email supprimé: ernestinejoynyangono@gmail.com
l'email supprimé: tsatedemstella@gmail.com
l'email supprimé: demsoungywetraissa@gmail.com
✅ Synchronisation terminée avec succès !

In [53]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM membre_de_la_family")

#-- Vérifiez si l'email existe
for _, row in Family.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM membre_de_la_family WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO membre_de_la_family (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

l'email supprimé: inkoukam@gmail.com
l'email supprimé: belingdominique@gmail.com
l'email supprimé: tmicaremedurance@gmail.com
✅ Synchronisation terminée avec succès !

In [54]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM membre_adhérents")

#-- Vérifiez si l'email existe
for _, row in Adhérent.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM membre_adhérents WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO membre_adhérents (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

✅ Synchronisation terminée avec succès !

In [55]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM partenaires")

#-- Vérifiez si l'email existe
for _, row in Partenaire.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM partenaires WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO partenaires (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

✅ Synchronisation terminée avec succès !

In [56]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM elders")

#-- Vérifiez si l'email existe
for _, row in Elders.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM elders WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO elders (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

✅ Synchronisation terminée avec succès !

In [57]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM autres")

#-- Vérifiez si l'email existe
for _, row in Autres.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM autres WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO autres (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année, membership) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'], row['membership'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

l'email supprimé: kengnineslinedjo@gmail.com
✅ Synchronisation terminée avec succès !

In [58]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM general")

#-- Vérifiez si l'email existe
for _, row in df.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM general WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO general (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année, membership, pole_benevolat) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['Horodateur'], row['membership'], row['pole'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

l'email supprimé: derrickdang15@yahoo.fr
l'email supprimé: natachamomo10@gmail.com
l'email supprimé: unkouefouette@gmail.com
l'email supprimé: wafoghislain2@gmail.com
l'email supprimé: armeladelaidensegue@gmail.com
l'email supprimé: daawemh@gmail.com
l'email supprimé: alfredekango10@gmail.com
l'email supprimé: sommeleandelson@gmail.com
l'email supprimé: axeltagnef@gmail.com
l'email supprimé: mmakat71@gmail.com
l'email supprimé: inkoukam@gmail.com
l'email supprimé: kengnineslinedjo@gmail.com
l'email supprimé: amadoulabarang40@gmail.com
l'email supprimé: mbone.joel@gmail.com
l'email supprimé: salecharlesjr@gmail.com
l'email supprimé: belingdominique@gmail.com
l'email supprimé: arolkache@gmail.com
l'email supprimé: tmicaremedurance@gmail.com
l'email supprimé: ernestinejoynyangono@gmail.com
l'email supprimé: olivierbjules237@gmail.com
l'email supprimé: celestintinabiyoo@yahoo.fr
l'email supprimé: fredyfokou7@gmail.com
l'email supprimé: Aurelientchako@gmail.com
l'email supprimé: josapro3@gmail.com
l'email supprimé: bmohamadou194@gmail.com
l'email supprimé: tsatedemstella@gmail.com
l'email supprimé: demsoungywetraissa@gmail.com
✅ Synchronisation terminée avec succès !

In [59]:
# ✅ 3) Connexion MySQL
conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Annuaire",
  database="the_okwelians"
)
cursor = conn.cursor()


#✅ 4) Vider la table avant d'insérer (optionnel)
cursor.execute("DELETE FROM mentors")

#-- Vérifiez si l'email existe
for _, row in Mentor.iterrows():
    email = row['email']
    doublon_query = "SELECT COUNT(*) FROM mentors WHERE email = %s"
    cursor.execute(doublon_query, (email,))
    count = cursor.fetchone()[0]

    if count == 0 :

        sql = "INSERT INTO mentors (prénom, nom, téléphone1, téléphone2, email, sexe, age, diplôme, profession, structure, secteur, secteur_activité, pays_de_résidence, région_de_résidence, département_de_résidence, ville_de_résidence, région_origine, année_intervention, programme, année) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        values = (row['prénom'], row['nom'], row['téléphone1'], row['téléphone2'], row['email'], row['sexe'], row['age'], row['diplome'], row['profession'], row['structure'], row['secteur'], row['secteur_activite'], row['pays_de_residence'], row['region_de_residence'], row['departement_de_residence'], row['ville_de_residence'], row['region_origine'], row['année_intervention'],row['programme_intervention'], row['Horodateur'])
        cursor.execute(sql, values)

    else : 

         print("l'email supprimé:", email)
         

conn.commit()

# ✅ 6) Fermer la connexion
cursor.close()
conn.close()

        


  
print("✅ Synchronisation terminée avec succès !")

✅ Synchronisation terminée avec succès !